[package]
name = "advent-of-code-2019"
version = "0.1.0"
authors = ["Ole Martin Ruud"]
edition = "2018"

[lib]
bench = false

[dependencies]
aoc-runner = "0.2"
aoc-runner-derive = "0.2"
nalgebra = "0.19.0"

[dev-dependencies]
criterion = "0.2"
